name: Setup Mise
description: Install mise and configure tools

runs:
  using: composite
  steps:
    - name: Install mise
      run: curl https://mise.run | sh
      shell: bash

    - uses: actions/cache@v5
      with:
        path: ~/.local/share/mise
        key: mise-${{ runner.os }}-${{ hashFiles('**/mise.toml') }}

    - name: Install tools
      run: mise install
      shell: bash

    - name: Add Shims to PATH
      run: echo "$HOME/.local/share/mise/shims" >> "$GITHUB_PATH"
      shell: bash
