name: PR

on:
  pull_request:
    types: [labeled, opened, synchronize]

permissions:
  deployments: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "Hello, world!"
      - run: sleep 60
